<?php

namespace LDL\Http\Api\Service\Application\Endpoint\Writer\Options;

class EndpointWriterOptions
{
    public const DEFAULT_FILENAME = 'autogenerated-endpoint.json';
    /**
     * @var string
     */
    private $file = self::DEFAULT_FILENAME;

    /**
     * @var string
     */
    private $source;

    /**
     * @var bool
     */
    private $force = false;

    /**
     * @var string
     */
    private $filePerms = '0666';

    public static function fromArray(array $options) : self
    {
        $instance = new static();
        $defaults = $instance->toArray();
        $merge = array_merge($defaults, $options);

        return $instance->setFile($merge['file'])
            ->setSource($merge['source'])
            ->setFilePerms($merge['filePerms'])
            ->setForce($merge['force']);
    }

    /**
     * @return array
     */
    public function toArray() : array
    {
        return get_object_vars($this);
    }

    /**
     * @return array
     */
    public function jsonSerialize() : array
    {
        return $this->toArray();
    }

    /**
     * @return string
     */
    public function getRealPath(): string
    {
        return sprintf(
            '%s%s%s',
            $this->getSource(),
            DIRECTORY_SEPARATOR,
            $this->getFile()
        );
    }

    /**
     * @return string
     */
    public function getFile(): string
    {
        return $this->file;
    }

    /**
     * @param string $file
     * @return EndpointWriterOptions
     */
    private function setFile(string $file): EndpointWriterOptions
    {
        $this->file = $file;
        return $this;
    }

    /**
     * @return string
     */
    public function getSource(): string
    {
        return $this->source ?? getcwd();
    }

    /**
     * @param string $source
     * @return EndpointWriterOptions
     */
    private function setSource(string $source): EndpointWriterOptions
    {
        $this->source = $source;
        return $this;
    }

    /**
     * @return bool
     */
    public function isForce(): bool
    {
        return $this->force;
    }

    /**
     * @param bool $force
     * @return EndpointWriterOptions
     */
    private function setForce(bool $force): EndpointWriterOptions
    {
        $this->force = $force;
        return $this;
    }

    /**
     * @return string
     */
    public function getFilePerms(): string
    {
        return $this->filePerms;
    }

    /**
     * @param string $filePerms
     * @return EndpointWriterOptions
     */
    private function setFilePerms(string $filePerms): EndpointWriterOptions
    {
        $this->filePerms = $filePerms;
        return $this;
    }
}